// Every user-facing string in the app lives here — DESIGN.md §7 and
// CONTEXT.md's glossary are enforced by having exactly one place strings can
// drift from them. No component may inline a string literal for copy.

export const copy = {
  wordmark: 'Split Bill',
  topBar: {
    exit: 'Exit',
  },
  start: {
    tagline: 'Photograph the receipt. Tag who had what.',
    photographReceipt: 'Photograph receipt',
    enterManually: 'Enter manually',
    photoNeverStored: 'Your photo is never stored.',
    resume: 'Resume',
    newBill: 'New Bill',
    newBillWarningTitle: "This discards the Bill you're working on",
    newBillWarningBody: 'Starting a New Bill discards the current Bill. This cannot be undone.',
    confirmNewBill: 'Discard and start new',
    cancelNewBill: 'Cancel',
    howItWorksTitle: 'How it works',
    howItWorks: [
      {
        title: 'Photograph the receipt',
        body: 'Snap a photo, or enter items by hand. Either way, nothing leaves your device.',
      },
      {
        title: 'Tag who had what',
        body: 'Assign each Line Item to a Diner. Shared plates split between everyone with a tap.',
      },
      {
        title: 'Get your Split',
        body: 'Adjustments are shared pro-rata by what each Diner ordered — automatically, every time.',
      },
    ],
    featuresTitle: 'Why Split Bill',
    features: [
      {
        title: 'Nothing stored',
        body: 'No accounts, no server holding your Bill. It exists only on this device.',
      },
      {
        title: 'Fair by default',
        body: 'The Split accounts for exactly what each Diner ordered, not an even share.',
      },
      {
        title: 'No sign-up',
        body: 'Open it and start. No account, no install, nothing to wait on.',
      },
    ],
    footerTagline: 'No accounts. Nothing leaves your device.',
  },
  capture: {
    heading: 'Photograph receipt',
    cameraLabel: 'Take photo',
    libraryLabel: 'Choose from library',
    dropzoneLabel: 'Drag a photo here, or choose a file',
    dropzoneHint: 'JPEG or PNG',
    webcamLabel: 'Use webcam',
    webcamCapture: 'Capture photo',
    webcamCancel: 'Cancel',
    webcamUnavailable: "Camera isn't available on this device.",
    enterManually: 'Enter manually instead',
    photoNeverStored: 'Your photo is never stored.',
  },
  parsing: {
    heading: 'Reading your receipt',
    stepUploading: 'Uploading photo',
    stepReading: 'Reading receipt',
    cancel: 'Cancel',
  },
  parseFailure: {
    offlineHeading: "You're offline",
    offlineBody: 'Check your connection and try again, or enter the Bill by hand.',
    rateLimitedHeading: 'Too many photos, too fast',
    rateLimitedBody: 'Wait a moment and try again, or enter the Bill by hand.',
    parseFailedHeading: "Couldn't read that receipt",
    parseFailedBody: 'The photo may be blurry or too dark. Try again, or enter the Bill by hand.',
    enterManually: 'Enter Bill by hand',
    retry: 'Try again',
  },
  billEditor: {
    reconciliationMatch: 'Matches the receipt total.',
    reconciliationMismatchHeading: "Doesn't match the receipt",
    reconciliationComputed: 'Computed',
    reconciliationPrinted: 'Printed',
    reconciliationDifference: 'Difference',
    place: 'Place',
    placePlaceholder: 'Add a place',
    date: 'Date',
    addPlaceAndDate: 'Add place and date',
    currency: 'Currency',
    currencyLockedHint: 'Remove every Line Item and Adjustment to change the currency.',
    lineItemsHeading: 'Line Items',
    lineItemsEmpty: 'No Line Items yet.',
    adjustmentsEmpty: 'No Adjustments yet.',
    lineItemName: 'Line item name',
    lineItemFallbackName: 'line item',
    quantity: 'Quantity',
    increaseQuantity: 'Increase quantity —',
    decreaseQuantity: 'Decrease quantity —',
    unitPrice: 'Unit price',
    lineTotal: 'Line total',
    addLineItem: 'Add Line Item',
    subtotal: 'Subtotal',
    adjustmentsHeading: 'Adjustments',
    adjustmentName: 'Adjustment name',
    adjustmentFallbackName: 'adjustment',
    adjustmentKind: 'Adjustment type',
    rate: 'Rate',
    fixed: 'Fixed',
    ratePercent: 'Rate percent',
    fixedAmount: 'Fixed amount',
    resolvesTo: 'Resolves to',
    addAdjustment: 'Add Adjustment',
    moveUp: 'Move up',
    moveDown: 'Move down',
    removeLineItem: 'Remove',
    removeAdjustment: 'Remove',
    total: 'Total',
    continueToDiners: 'Diners',
  },
  dinerSetup: {
    heading: 'Diners',
    rememberedHeading: 'Used before',
    forgetName: 'Forget',
    nameField: 'Diner name',
    namePlaceholder: 'Add a Diner',
    addDiner: 'Add',
    dinersEmpty: 'No Diners yet. Add the first one above.',
    renameDiner: 'Diner name',
    removeDiner: 'Remove',
    markAsPayer: 'Mark as Payer',
    payerBadge: 'Payer',
    unmarkAsPayer: 'Remove as Payer',
    continueToAssignment: 'Assignment',
  },
  assignment: {
    lineItemsEmpty: 'No Line Items to assign.',
    assignRow: 'Assign',
    unclaimedHint: 'Unclaimed',
    pickerDone: 'Done',
    pickerNoClaims: 'No one has claimed this yet.',
    stepperDecrease: 'Decrease Shares —',
    stepperIncrease: 'Increase Shares —',
    adjustmentsUnassignableNote: "Adjustments are split automatically and can't be assigned to a Diner.",
    incompleteSplitHeading: 'Incomplete Split',
    incompleteSplitTrailer: 'unclaimed',
    divideRemainder: 'Split the rest between everyone',
    continueToSummary: 'Summary',
  },
  summary: {
    heading: 'Summary',
    isOwed: 'is owed',
    billTotal: 'Bill total',
    payLine: 'Pay',
    shareText: 'Share summary',
    shareTextCopied: 'Summary copied to clipboard',
    shareImage: 'Share image',
    shareImageCopied: 'Image copied to clipboard',
    shareImageDownloaded: 'Image downloaded',
  },
} as const
