// Every user-facing string in the app lives here — DESIGN.md §7 and
// CONTEXT.md's glossary are enforced by having exactly one place strings can
// drift from them. No component may inline a string literal for copy.

export const copy = {
  wordmark: 'Split Bill',
  topBar: {
    exit: 'Exit',
    history: 'History',
  },
  start: {
    headline: 'Split the bill, not the friendship',
    returningTitle: 'You have a Bill in progress',
    // "Scan", never "Photograph" — issue #23's copy correction; kept even
    // though the mockup's own hero subhead says "Photograph".
    tagline: 'Scan a receipt or type it in — Split Bill figures out who owes what, in seconds.',
    photographReceipt: 'Scan a receipt',
    enterManually: 'Enter manually instead',
    photoNeverStored: 'Your receipt photo is never stored.',
    resume: 'Resume this Bill',
    newBill: 'Start a New Bill',
    newBillWarningTitle: "This discards the Bill you're working on",
    newBillWarningBody: 'Starting a New Bill discards the one in progress. This cannot be undone.',
    confirmNewBill: 'Discard and start new',
    cancelNewBill: 'Cancel',
    howItWorksTitle: 'How it works',
    howItWorks: [
      {
        title: 'Snap or type',
        body: 'the Line Items on your receipt',
      },
      {
        title: 'Add Diners',
        body: 'tap who claims each item',
      },
      {
        title: 'Get a Summary',
        body: 'and share it',
      },
    ],
    features: ['No accounts. Nothing leaves your browser.', 'Works in IDR, SGD, USD, EUR, GBP, JPY, AUD, MYR.'],
    footerNote: 'Your receipt photo is never stored — nothing is uploaded to a server.',
    receiptPreview: {
      place: 'The Warung',
      items: [
        { name: 'Nasi Goreng ×2', amount: '13.00' },
        { name: 'Iced Tea ×3', amount: '9.00' },
      ],
      total: '$25.89',
    },
  },
  capture: {
    heading: 'Scan receipt',
    cameraLabel: 'Scan photo',
    libraryLabel: 'Choose from library',
    dropzoneLabel: 'Drag a photo here, or choose a file',
    dropzoneHint: 'JPEG or PNG',
    webcamLabel: 'Use webcam',
    webcamCapture: 'Capture photo',
    webcamCancel: 'Cancel',
    webcamUnavailable: "Camera isn't available on this device.",
    enterManually: 'Enter manually instead',
    photoNeverStored: 'Your photo is never stored.',
  },
  parsing: {
    heading: 'Reading your receipt',
    stepUploading: 'Uploading photo',
    stepReading: 'Reading receipt',
    cancel: 'Cancel',
  },
  parseFailure: {
    offlineHeading: "You're offline",
    offlineBody: 'Check your connection and try again, or enter the Bill by hand.',
    rateLimitedHeading: 'Too many photos, too fast',
    rateLimitedBody: 'Wait a moment and try again, or enter the Bill by hand.',
    parseFailedHeading: "Couldn't read that receipt",
    parseFailedBody: 'The photo may be blurry or too dark. Try again, or enter the Bill by hand.',
    enterManually: 'Enter Bill by hand',
    retry: 'Try again',
  },
  billEditor: {
    reconciliationMatch: 'Matches the receipt total.',
    reconciliationMismatchHeading: "Doesn't match the receipt",
    reconciliationComputed: 'Computed',
    reconciliationPrinted: 'Printed',
    reconciliationDifference: 'Difference',
    place: 'Place',
    placePlaceholder: 'Add a place',
    date: 'Date',
    addPlaceAndDate: 'Add place and date',
    currency: 'Currency',
    currencyLockedHint: 'Remove every Line Item and Adjustment to change the currency.',
    lineItemsHeading: 'Line Items',
    lineItemsEmpty: 'No Line Items yet.',
    adjustmentsEmpty: 'No Adjustments yet.',
    lineItemName: 'Line item name',
    lineItemFallbackName: 'line item',
    quantity: 'Quantity',
    increaseQuantity: 'Increase quantity —',
    decreaseQuantity: 'Decrease quantity —',
    unitPrice: 'Unit price',
    lineTotal: 'Line total',
    addLineItem: 'Add Line Item',
    subtotal: 'Subtotal',
    adjustmentsHeading: 'Adjustments',
    adjustmentName: 'Adjustment name',
    adjustmentFallbackName: 'adjustment',
    adjustmentKind: 'Adjustment type',
    rate: 'Rate',
    fixed: 'Fixed',
    ratePercent: 'Rate percent',
    fixedAmount: 'Fixed amount',
    resolvesTo: 'Resolves to',
    addAdjustment: 'Add Adjustment',
    moveUp: 'Move up',
    moveDown: 'Move down',
    removeLineItem: 'Remove',
    removeAdjustment: 'Remove',
    total: 'Total',
    continueToDiners: 'Diners',
  },
  dinerSetup: {
    heading: 'Diners',
    rememberedHeading: 'Used before',
    forgetName: 'Forget',
    nameField: 'Diner name',
    namePlaceholder: 'Add a Diner',
    addDiner: 'Add',
    dinersEmpty: 'No Diners yet. Add the first one above.',
    renameDiner: 'Diner name',
    removeDiner: 'Remove',
    markAsPayer: 'Mark as Payer',
    payerBadge: 'Payer',
    unmarkAsPayer: 'Remove as Payer',
    continueToAssignment: 'Assignment',
  },
  assignment: {
    lineItemsEmpty: 'No Line Items to assign.',
    dinersHeading: 'Diners',
    assignRow: 'Assign',
    unclaimedHint: 'Unclaimed',
    pickerDone: 'Done',
    pickerNoClaims: 'No one has claimed this yet.',
    stepperDecrease: 'Decrease Shares —',
    stepperIncrease: 'Increase Shares —',
    adjustmentsUnassignableNote: "Adjustments are split automatically and can't be assigned to a Diner.",
    incompleteSplitHeading: 'Incomplete Split',
    incompleteSplitTrailer: 'unclaimed',
    divideRemainder: 'Split the rest between everyone',
    continueToSummary: 'Summary',
  },
  summary: {
    heading: 'Summary',
    isOwed: 'is owed',
    billTotal: 'Bill total',
    payLine: 'Pay',
    copyText: 'Copy text',
    textCopied: 'Summary copied to clipboard',
    downloadImage: 'Download image',
    imageDownloaded: 'Image downloaded',
  },
  history: {
    heading: 'History',
    empty: "This fills in as Bills are finished or discarded — nothing's archived yet.",
    untitledPlace: 'Untitled Bill',
    archivedOn: 'Archived',
  },
} as const
